---
title: "data-dictionary.md"
output: html_document
---

team_name: character; Golden State Warriors.
game_date: character; indicates the time when the game played.
season: integer; the NBA season.
period: integer; an NBA game is divided in 4 periods of 12 mins each. For example, a value for period = 1 refers to the first period (the first 12 mins of the game).
minutes_remaining: integer; the amount of time in minutes that remained to be played in a given period.
seconds_remaining: integer; the amount of time in seconds that remained to be played in a given period.
shot_made_flag: character; shot_made_flag indicates whether a shot was made (y) or missed (n).
action_type: factor; action_type has to do with the basketball moves used by players, either to pass by defenders to gain access to the basket, or to get a clean pass to a teammate to score a two pointer or three pointer.
shot_type: factor; shot_type indicates whether a shot is a 2-point field goal, or a 3-point field goal.
shot_distance: integer; shot_distance: distance to the basket (measured in feet).
opponent: character; the opponent of the game.
x,y: integer; x and y refer to the court coordinates (measured in inches) where a shot occurred .
name: character; the player's name.

